DEP Update dependency versions
silverstripe/recipe-kitchen-sink pull request #1
Opened 2021-08-29 22:06 UTC by emteknetnz

2021-09-03 00:44 UTC, maxime-rainville requested changes

2021-09-03 00:44 UTC, maxime-rainville commented on composer.json
> +        "tractorcow/silverstripe-fluent": "4.1.x-dev"
```suggestion
        "tractorcow/silverstripe-fluent": "4.5.x-dev"
```

2021-09-03 02:59 UTC, emteknetnz commented
Updated

2021-09-03 03:38 UTC, maxime-rainville approved these changes
Looks good. Let's maybe wait until https://github.com/silverstripe/recipe-form-building/pull/14 and and https://github.com/silverstripe/cwp-recipe-search/pull/19 are merged before merging this one.

2021-09-06 03:23 UTC, maxime-rainville commented
Merging despite broken build so we can get the CI running against the correct branches.

2021-09-06 03:23 UTC, merged