DEP Remove modules that have no tests
silverstripe/recipe-kitchen-sink pull request #4
Opened 2021-11-17 04:04 UTC by emteknetnz

- Adds testsuites node for phpunit 9
- Remove vendor/symbiote/silverstripe-errorpage/tests
- Remove vendor/colymba/gridfield-bulk-editing-tools/tests
- Remove vendor/dnadesign/silverstripe-elemental-subsites/tests
- Remove vendor/bringyourownideas/silverstripe-composer-security-checker/tests

2021-11-18 03:01 UTC, maxime-rainville requested changes
Swap `symbiote/silverstripe-errorpage` with `silverstripe/errorpage`. Everything else looks fine.

Left notes on the removed module for posterity in case someone ever wonders why those got removed.

2021-11-18 03:01 UTC, maxime-rainville commented on phpunit.xml.dist
> -        <directory>vendor/symbiote/silverstripe-errorpage/tests</directory>
This was probably a mistake and was probably meant to test `silverstripe/errorpage` which does have tests. Can we swap it in instead?

2021-11-18 03:01 UTC, maxime-rainville commented on phpunit.xml.dist
> -        <directory>mysite/tests</directory>
This is removed because we don't have any test there.

2021-11-18 03:01 UTC, maxime-rainville commented on phpunit.xml.dist
> -        <directory>vendor/silverstripe/controllerpolicy/tests</directory>
Controller policy is being removed from the sink.

2021-11-18 03:01 UTC, maxime-rainville commented on phpunit.xml.dist
> -        <directory>vendor/colymba/gridfield-bulk-editing-tools/tests</directory>
Doesn't have any CI

2021-11-18 03:01 UTC, maxime-rainville commented on phpunit.xml.dist
> -        <directory>vendor/dnadesign/silverstripe-elemental-subsites/tests</directory>
This module is not part of the sink.

2021-11-18 03:01 UTC, maxime-rainville commented on phpunit.xml.dist
> -        <directory>vendor/bringyourownideas/silverstripe-composer-security-checker/tests</directory>
composer-security-checker was removed from the sink a while back

2021-11-18 20:30 UTC, emteknetnz commented on phpunit.xml.dist
> -        <directory>vendor/symbiote/silverstripe-errorpage/tests</directory>
Done

2021-11-22 00:24 UTC, maxime-rainville approved these changes
Looks good ... I'll merge now since this change won't break or fix build by itself.

2021-11-22 00:24 UTC, merged