MNT Run module-standardiser
silverstripe/recipe-kitchen-sink pull request #60
Opened 2024-05-15 22:19 UTC by emteknetnz

This pull-request was created automatically by [module-standardiser](https://github.com/silverstripe/module-standardiser)

2024-05-16 22:16 UTC, GuySartorelli requested changes
This PR adds the phpstan stuff, but no phplinting job is in the CI run. We should either not include phpstan stuff for recipes, or make sure to include PHP linting in their CI runs.

I'd suggest not including it - everything in a recipe is included in projects and I don't think we want projects to have our idiosyncratic module-related standards enforced.

2024-05-16 22:40 UTC, emteknetnz commented
Have removed and updated module-standardiser to not include it in future 
- https://github.com/silverstripe/module-standardiser/pull/50

2024-05-16 22:42 UTC, GuySartorelli requested changes

2024-05-16 22:42 UTC, GuySartorelli commented on composer.json
> +        "phpstan/extension-installer": "^1.3"
```suggestion
        "mikey179/vfsstream": "^1.6"
```

2024-05-16 22:52 UTC, emteknetnz commented on composer.json
> +        "phpstan/extension-installer": "^1.3"
Updated

2024-05-17 00:37 UTC, GuySartorelli approved these changes
LGTM

2024-05-17 00:37 UTC, merged